[package]
name = "dynamic_bot"
version = "0.1.0"
authors = ["Niraj Amalkanti <namalkanti@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"]}
serde_yaml = "0.8"

[dependencies.serenity]
default-features = true
features = ["voice"]
version = "0.8"

